### PR TITLE
[MRG] New chapter on statistics in Python

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
Includes an update of gen_rst.py, which ended being necessary.

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
I have rebased on master, and finished the content. Someone cares to review?

**Comment by GaelVaroquaux** [comment]
Tests pass on python 3!

Hurray.

Can I have a review. This is ready for merge.

File: .travis.yml [hunk 1]
```diff
@@ -12,13 +12,17 @@ env:
   matrix:
     # Ubuntu 14.04 versions
     - DISTRIB="conda" PYTHON_VERSION="$TRAVIS_PYTHON_VERSION"
-      NUMPY_VERSION="1.8.2" SCIPY_VERSION="0.14.0" 
-      SCIKIT_LEARN_VERSION="0.15.1" MATPLOTLIB_VERSION="1.4.0"
+      NUMPY_VERSION="1.9" SCIPY_VERSION="0.14.0" 
+      SCIKIT_LEARN_VERSION="0.16.1" MATPLOTLIB_VERSION="1.4.0"
```
Comment (emmanuelle) [inline .travis.yml]: Why this change? Did you rebase on master after #185 was merged? ``scikit-learn`` 0.16 is not packaged in the latest Ubuntu.

File: .travis.yml [hunk 2]
```diff
@@ -12,13 +12,17 @@ env:
...
       SCIKIT_IMAGE_VERSION="0.10.1" SYMPY_VERSION="0.7.5"
+      STATSMODELS_VERSION="0.5" SEABORN_VERSION="0.6"
+      PANDAS_VERSION="0.15"
     - DISTRIB="conda" PYTHON_VERSION="3.4"
-      NUMPY_VERSION="1.8.2" SCIPY_VERSION="0.14.0" 
-      SCIKIT_LEARN_VERSION="0.15.1" MATPLOTLIB_VERSION="1.4.0"
+      NUMPY_VERSION="1.9" SCIPY_VERSION="0.14.0" 
+      SCIKIT_LEARN_VERSION="0.16.1" MATPLOTLIB_VERSION="1.4.0"
```
Comment (emmanuelle) [inline .travis.yml]: same here

File: .travis.yml (hunk 1 above)
Comment (GaelVaroquaux) [inline .travis.yml]: > Why this change? Did you rebase on master after #185 was merged? scikit-learn
> 0.16 is not packaged in the latest Ubuntu.

To be able to have seaborn and pandas installed. Conda has exclusion
rules that make it impossible to replicate an ubuntu install.

File: intro/scipy.rst [hunk 3]
```diff
@@ -560,8 +557,10 @@ the random process's PDF (probability density function): ::
 
 .. sourcecode:: ipython
```
Comment (emmanuelle) [inline intro/scipy.rst]: remove

File: packages/statistics/examples/plot_airfare.py [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+
+if not os.path.exists('airfares.txt'):
+    # Download the file if it is not present
+    urllib.urlretrieve(
+        'http://www.stat.ufl.edu/~winner/data/airq4.dat',
+                       'airfares.txt')
+
+# As a seperator, ' +' is a regular expression that means 'one of more
+# space'
+data = pandas.read_csv('clinical.txt', sep=' +', header=0,
```
Comment (emmanuelle) [inline packages/statistics/examples/plot_airfare.py]: airfares.txt ?

File: packages/statistics/examples/plot_airfare.py [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+
+data_flat = pandas.concat([data_2000, data_2001])
+
+
+##############################################################################
+# Plot scatter matrices highlighting different aspects
+
+import seaborn
+seaborn.pairplot(data_flat, vars=['fare', 'dist', 'nb_passengers'],
+                 kind='reg', markers='.')
```
Comment (emmanuelle) [inline packages/statistics/examples/plot_airfare.py]: does not work with seaborn 0.4 (packaged in ubuntu universe), only with 0.6 packaged in neurodebian
```
TypeError: pairplot() got an unexpected keyword argument 'markers'
```

File: packages/statistics/examples/plot_airfare.py [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+
+# A second plot, to show the effect of the year (ie the 9/11 effect)
+seaborn.pairplot(data_flat, vars=['fare', 'dist', 'nb_passengers'],
+                 kind='reg', hue='year', markers='.')
```
Comment (emmanuelle) [inline packages/statistics/examples/plot_airfare.py]: same here

File: packages/statistics/index.rst [hunk 7]
```diff
@@ -0,0 +1,849 @@
...
+   * Standard scientific Python environment (numpy, scipy, matplotlib)
+
+   * `Pandas <http://pandas.pydata.org/>`_
+
+   * `Statsmodels <http://statsmodels.sourceforge.net/>`_
+
+   * `Seaborn <http://stanford.edu/~mwaskom/software/seaborn/>`_
+
+   To install Python and these dependencies, we recommend that you
+   download `Anaconda Python <http://continuum.io/downloads>`_, or use
```
Comment (emmanuelle) [inline packages/statistics/index.rst]: or `Enthought Canopy <https://store.enthought.com/>`_

File: packages/statistics/index.rst [hunk 8]
```diff
@@ -0,0 +1,849 @@
...
+   <http://pymc-devs.github.io/pymc>`_, which implements a probabilistic
+   programming language in Python.
+
+|
+
+.. tip::
+
+    **Why Python for statistics?**
+
+    R is a language dedicated to statistics. Python is a general purpose
```
Comment (emmanuelle) [inline packages/statistics/index.rst]: general-purpose

File: packages/statistics/index.rst [hunk 9]
```diff
@@ -0,0 +1,849 @@
...
+    ">>>". To copy-paste code, you can click on the top right of the code
+    blocks, to hide the prompts and the outputs.
+
+    |
+
+    **Disclaimer: Gender questions**
+
+    Some of the examples of this tutorial are chosen around touchy
+    gender questions. The reason is that on such questions the true
+    value of a claim actually matters to many people.
```
Comment (emmanuelle) [inline packages/statistics/index.rst]: formulation could be improved

File: packages/statistics/index.rst [hunk 10]
```diff
@@ -0,0 +1,849 @@
...
+Data representation and interaction
+====================================
+
+Data as a table
+----------------
+
+The setting that we consider for statistical analysis is that of multiple
+*observations* or *samples* described by a set of different *attributes*
+or *features*. The data can than be seen as a 2D table, or matrix, with
+columns given the different attributes of the data, and rows the
```
Comment (emmanuelle) [inline packages/statistics/index.rst]: giving

File: packages/statistics/index.rst [hunk 11]
```diff
@@ -0,0 +1,849 @@
...
+
+The panda data-frame
+------------------------
+
+.. tip::
+
+    We will store and manipulate this data in a
+    :class:`pandas.DataFrame`, from the `pandas
+    <http://pandas.pydata.org>`_ module. It is the Python equivalent of
+    the spreadsheet table. It is different from a 2D numpy array as it
```
Comment (emmanuelle) [inline packages/statistics/index.rst]: ``numpy`` or NumPy

File: packages/statistics/index.rst [hunk 12]
```diff
@@ -0,0 +1,849 @@
...
+    has named columns, can contained a mixture of different data types by
```
Comment (emmanuelle) [inline packages/statistics/index.rst]: can contain

File: packages/statistics/index.rst [hunk 13]
```diff
@@ -0,0 +1,849 @@
...
+.. warning:: **Missing values**
+
+   The weight of the second individual is missing in the CSV file. If we
+   don't specify the missing value (NA = not available) marker, we will
+   not be able to do statistical analysis.
+
+|
+
+**Creating from arrays**: A :class:`pandas.DataFrame` can also be seen
+as a dictionary of 1D 'series', eg arrays or lists. If we have 3 numpy
```
Comment (emmanuelle) [inline packages/statistics/index.rst]: same here for numpy

File: packages/statistics/index.rst [hunk 14]
```diff
@@ -0,0 +1,849 @@
...
+    >>> print(data['Gender'])  # Columns can be addressed by name   # doctest: +ELLIPSIS
+    0     Female
+    1       Male
+    2       Male
+    3       Male
+    4     Female
+    ...
+
+    >>> # Simpler selector
+    >>> data[data['Gender'] == 'Female']['VIQ'].mean()
```
Comment (emmanuelle) [inline packages/statistics/index.rst]: I find
```
data[data.Gender == 'Female'].VIQ.mean()
```
to be easier to read and type. But I'm not a pandas specialist at all, so maybe there are good reasons that I don't know of to use the other notation.

Comment (emmanuelle) [inline packages/statistics/index.rst]: Well, pandas' documentation use both notations but seems to prefer the indexing-like one, at least for simple expressions.

File: packages/statistics/index.rst [hunk 15]
```diff
@@ -0,0 +1,849 @@
...
+**groupby**: splitting a dataframe on values of categorical variables::
+
+    >>> groupby_gender = data.groupby('Gender')
+    >>> for gender, value in groupby_gender['VIQ']:
+    ...     print((gender, value.mean()))
+    ('Female', 109.45)
+    ('Male', 115.25)
+
+
+`groupby_gender` is a powerfull object that exposes many
```
Comment (emmanuelle) [inline packages/statistics/index.rst]: powerful

File: packages/statistics/index.rst [hunk 16]
```diff
@@ -0,0 +1,849 @@
...
+
+.. topic:: **Exercice**
+   :class: green
+
+   * Test the difference between weights in males and females.
+
+   * Use non parametric statistics to test the difference between VIQ in
+     males and females.
+
+|
```
Comment (emmanuelle) [inline packages/statistics/index.rst]: Some conclusions here? If I understand well, comparing VIQs of male and female shows that one cannot reject that the two quantities have the same mean (p-value of 0.44..), but it might help the reader to write it in so many words.

**Comment by GaelVaroquaux** [comment]
I addressed all the comments.Thank you for reviewing. I am merging.
